"""recommended ap, f and Vc(f) of tools

Revision ID: 0558af27f2f6
Revises: 157413ef972d
Create Date: 2026-10-07 18:37:38.528664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0558af27f2f6'
down_revision = '157413ef972d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ap_rec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f_rec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vc_points', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('vc_points')
        batch_op.drop_column('f_rec')
        batch_op.drop_column('ap_rec')

    # ### end Alembic commands ###
