"""cutting force of materials and drive efficiency

Revision ID: 09577df41fd1
Revises: 13d9cb0e4528
Create Date: 2026-10-06 19:32:14.785794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09577df41fd1'
down_revision = '13d9cb0e4528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_efficiency', sa.Float(), nullable=True))

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kc1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kc_source', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###

    # The seed materials of an existing database get the same placeholder kc1 / mc as a new seed (by name, only
    # where none is set). Values copied here so the migration does not change with seed.py.
    material = sa.table("material", sa.column("name", sa.String), sa.column("kc1", sa.Float),
                        sa.column("mc", sa.Float), sa.column("kc_source", sa.String))
    source = "PLACEHOLDER: catalogue-type value for {} (e.g. Sandvik Coromant {}), not verified"
    for name, kc1, mc, group, code in (
        ("Steel 45 (C45)", 1600, 0.25, "ISO P unalloyed steel", "P1.2"),
        ("AISI 304", 2000, 0.21, "ISO M austenitic stainless steel", "M2"),
        ("Aluminium 6061", 600, 0.25, "ISO N wrought aluminium alloy", "N1.2"),
    ):
        op.execute(
            material.update()
            .where(material.c.name == name, material.c.kc1.is_(None))
            .values(kc1=kc1, mc=mc, kc_source=source.format(group, code))
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('kc_source')
        batch_op.drop_column('mc')
        batch_op.drop_column('kc1')

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('drive_efficiency')

    # ### end Alembic commands ###
