"""initial schema

Revision ID: 0a62a8b2ac24
Revises: 
Create Date: 2026-09-27 06:27:11.970885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a62a8b2ac24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_rpm', sa.Integer(), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('max_diameter', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_group', sa.String(length=1), nullable=False),
    sa.Column('hardness_hb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('insert_code', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=30), nullable=True),
    sa.Column('iso_group', sa.String(length=10), nullable=False),
    sa.Column('vc_min', sa.Float(), nullable=False),
    sa.Column('vc_max', sa.Float(), nullable=False),
    sa.Column('f_min', sa.Float(), nullable=False),
    sa.Column('f_max', sa.Float(), nullable=False),
    sa.Column('ap_min', sa.Float(), nullable=False),
    sa.Column('ap_max', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('blank_diameter', sa.Float(), nullable=False),
    sa.Column('blank_length', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turret_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'position')
    )
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('tolerance', sa.String(length=30), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('turret_position', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_type', sa.String(length=30), nullable=False),
    sa.Column('rough_finish', sa.String(length=10), nullable=False),
    sa.Column('vc', sa.Float(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('f', sa.Float(), nullable=True),
    sa.Column('ap', sa.Float(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('ref_diameter', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('calculation_version', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=30), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edit')
    op.drop_table('operation')
    op.drop_table('feature')
    op.drop_table('turret_slot')
    op.drop_table('job')
    op.drop_table('tool')
    op.drop_table('material')
    op.drop_table('machine')
    # ### end Alembic commands ###
