"""max thread feed of the machine

Revision ID: 13d9cb0e4528
Revises: d5838ef1ecf1
Create Date: 2026-10-06 19:16:07.358648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d9cb0e4528'
down_revision = 'd5838ef1ecf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_thread_feed', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('max_thread_feed')

    # ### end Alembic commands ###
