"""tool source, retired, updated_at; operation created_at

Revision ID: 157413ef972d
Revises: e057e67f3716
Create Date: 2026-10-07 05:23:22.898199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157413ef972d'
down_revision = 'e057e67f3716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_retired', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_retired')
        batch_op.drop_column('source')

    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
