"""programming values of the machine, G-code set-up of a job

Revision ID: 209c6b4145de
Revises: e304ff3c2963
Create Date: 2026-10-09 05:32:07.253731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209c6b4145de'
down_revision = 'e304ff3c2963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_end', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('stickout_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('face_stock_mm', sa.Float(), nullable=True))

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spindle_right_hand', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('clearance_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clearance_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('retract_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('chuck_safety_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thread_run_in_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('peck_depth_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('facing_overshoot_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('groove_reference', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('groove_reference')
        batch_op.drop_column('facing_overshoot_mm')
        batch_op.drop_column('peck_depth_mm')
        batch_op.drop_column('thread_run_in_mm')
        batch_op.drop_column('chuck_safety_mm')
        batch_op.drop_column('retract_mm')
        batch_op.drop_column('clearance_z')
        batch_op.drop_column('clearance_x')
        batch_op.drop_column('spindle_right_hand')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('face_stock_mm')
        batch_op.drop_column('stickout_mm')
        batch_op.drop_column('free_end')

    # ### end Alembic commands ###
