"""cached drawing extractions

Revision ID: 244f24f1cdb4
Revises: 6bfce6b1457d
Create Date: 2026-09-27 17:30:33.606203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244f24f1cdb4'
down_revision = '6bfce6b1457d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_drawing_extraction_cached_from_id', 'drawing_extraction', ['cached_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_drawing_extraction_cached_from_id', type_='foreignkey')
        batch_op.drop_column('cached_from_id')

    # ### end Alembic commands ###
