"""drawing read mode

Revision ID: 25a52943b7b0
Revises: 7d05e6c60571
Create Date: 2026-09-27 18:33:50.412372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a52943b7b0'
down_revision = '7d05e6c60571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        batch_op.drop_column('read_mode')

    # ### end Alembic commands ###
