"""cutting data from catalogues

Revision ID: 339c93bf0976
Revises: ac2fb403c778
Create Date: 2026-10-08 19:23:17.240962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339c93bf0976'
down_revision = 'ac2fb403c778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('text_pages', sa.Integer(), nullable=False),
    sa.Column('selected_pages', sa.String(length=200), nullable=True),
    sa.Column('material_groups', sa.String(length=100), nullable=True),
    sa.Column('codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='uploaded', nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('read_pages', sa.String(length=200), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('not_taken', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cutting_data_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('catalogue', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('insert_code', sa.String(length=60), nullable=True),
    sa.Column('grade', sa.String(length=30), nullable=True),
    sa.Column('application', sa.String(length=12), nullable=True),
    sa.Column('material_group', sa.String(length=20), nullable=False),
    sa.Column('ap_min', sa.Float(), nullable=True),
    sa.Column('ap_rec', sa.Float(), nullable=True),
    sa.Column('ap_max', sa.Float(), nullable=True),
    sa.Column('f_min', sa.Float(), nullable=True),
    sa.Column('f_rec', sa.Float(), nullable=True),
    sa.Column('f_max', sa.Float(), nullable=True),
    sa.Column('vc_min', sa.Float(), nullable=True),
    sa.Column('vc_max', sa.Float(), nullable=True),
    sa.Column('vc_points', sa.String(length=200), nullable=True),
    sa.Column('coolant', sa.Boolean(), nullable=True),
    sa.Column('from_graph', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('page', sa.String(length=60), nullable=True),
    sa.Column('pdf_page', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='read', nullable=False),
    sa.Column('checks', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['catalogue_document.id'], name='fk_cutting_data_row_document_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogue_group', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###
    # The seed steel is Sandvik Coromant's P1.2 (docs/turnpilot_catalog_P1.2.md: "сталь 45 / C45 / EN8"); the other
    # seed materials have no checked group and stay empty.
    op.execute(sa.text("UPDATE material SET catalogue_group = 'P1.2' WHERE name = 'Steel 45 (C45)'"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('catalogue_group')

    op.drop_table('cutting_data_row')
    op.drop_table('catalogue_document')
    # ### end Alembic commands ###
