"""roughness parameter Ra or Rz

Revision ID: 3e15d67856d2
Revises: 25a52943b7b0
Create Date: 2026-09-28 19:39:22.634919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e15d67856d2'
down_revision = '25a52943b7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ra_param', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('ra_param')

    # ### end Alembic commands ###
