"""arc and fillet shape of a feature

Revision ID: 4db70aa0a7c8
Revises: d032e6444de3
Create Date: 2026-10-09 19:30:03.529462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db70aa0a7c8'
down_revision = 'd032e6444de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arc_convex', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('arc_convex')

    # ### end Alembic commands ###
