"""nose radius and tip direction of a tool

Revision ID: 500ead6679f1
Revises: c136fae484df
Create Date: 2026-10-10 05:23:23.976173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500ead6679f1'
down_revision = 'c136fae484df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nose_radius', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tip_direction', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('tip_direction')
        batch_op.drop_column('nose_radius')

    # ### end Alembic commands ###
