"""hex bar stock

Revision ID: 671327f4a6ea
Revises: b4e212a491e9
Create Date: 2026-09-29 05:59:05.839620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671327f4a6ea'
down_revision = 'b4e212a491e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blank_shape', sa.String(length=10), server_default='round', nullable=False))

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hex_bar_sizes', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('hex_bar_sizes')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('blank_shape')

    # ### end Alembic commands ###
