"""drawing extraction and feature confidence

Revision ID: 68bda29ef315
Revises: d9974d4be48c
Create Date: 2026-09-27 06:54:14.161535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bda29ef315'
down_revision = 'd9974d4be48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=100), nullable=False),
    sa.Column('sent_filename', sa.String(length=100), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    op.drop_table('drawing_extraction')
    # ### end Alembic commands ###
