"""feature radius for fillets

Revision ID: 6bfce6b1457d
Revises: 68bda29ef315
Create Date: 2026-09-27 17:24:47.670008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfce6b1457d'
down_revision = '68bda29ef315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radius', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('radius')

    # ### end Alembic commands ###
