"""prompt version of drawing extractions

Revision ID: 7d05e6c60571
Revises: 244f24f1cdb4
Create Date: 2026-09-27 17:37:42.566008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d05e6c60571'
down_revision = '244f24f1cdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_version', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        batch_op.drop_column('prompt_version')

    # ### end Alembic commands ###
