"""chamfer location and face

Revision ID: 9b0e4b54a5e3
Revises: 3e15d67856d2
Create Date: 2026-09-28 19:46:19.506674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0e4b54a5e3'
down_revision = '3e15d67856d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('face', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('face')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
