"""passport reading

Revision ID: ac2fb403c778
Revises: c96d2f7a7dcc
Create Date: 2026-10-08 19:03:53.607826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2fb403c778'
down_revision = 'c96d2f7a7dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=12), server_default='uploaded', nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('read_pages', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('raw_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reading', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_document', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('read_at')
        batch_op.drop_column('error')
        batch_op.drop_column('reading')
        batch_op.drop_column('raw_response')
        batch_op.drop_column('read_pages')
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('model')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
