"""hex across flats

Revision ID: b4e212a491e9
Revises: 9b0e4b54a5e3
Create Date: 2026-09-29 05:52:22.393486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e212a491e9'
down_revision = '9b0e4b54a5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('across_flats', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('across_flats')

    # ### end Alembic commands ###
