"""drawn radius of an arc

Revision ID: c136fae484df
Revises: 4db70aa0a7c8
Create Date: 2026-10-09 19:36:38.307568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c136fae484df'
down_revision = '4db70aa0a7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawn_radius', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('drawn_radius')

    # ### end Alembic commands ###
