"""machine data with sources

Revision ID: ccd02424ad60
Revises: 450337eecff1
Create Date: 2026-10-08 18:50:18.518795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd02424ad60'
down_revision = '450337eecff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_spec_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], name='fk_machine_spec_source_machine_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'field', name='uq_machine_spec_source_field')
    )
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_rpm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('power_s6_kw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_turning_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_bar_diameter', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('turret_positions', sa.Integer(), server_default='12', nullable=False))
        batch_op.add_column(sa.Column('max_z_feed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('coolant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('coolant_pressure_bar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('live_tooling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('c_axis', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('control', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('control')
        batch_op.drop_column('c_axis')
        batch_op.drop_column('live_tooling')
        batch_op.drop_column('coolant_pressure_bar')
        batch_op.drop_column('coolant')
        batch_op.drop_column('max_z_feed')
        batch_op.drop_column('turret_positions')
        batch_op.drop_column('max_bar_diameter')
        batch_op.drop_column('max_turning_length')
        batch_op.drop_column('power_s6_kw')
        batch_op.drop_column('min_rpm')

    op.drop_table('machine_spec_source')
    # ### end Alembic commands ###
