"""G-code programs, demo set-up flag

Revision ID: d032e6444de3
Revises: d82ea01ebe01
Create Date: 2026-10-09 18:56:20.482277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd032e6444de3'
down_revision = 'd82ea01ebe01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcode_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('calculation_version', sa.Integer(), nullable=False),
    sa.Column('dialect', sa.String(length=60), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('settings', sa.Text(), nullable=False),
    sa.Column('simulation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='simulated', nullable=False),
    sa.Column('checklist', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='fk_gcode_program_job_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gcode_setup_demo', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('gcode_setup_demo')

    op.drop_table('gcode_program')
    # ### end Alembic commands ###
