"""axial order known of jobs

Revision ID: d5838ef1ecf1
Revises: db9bd888d36a
Create Date: 2026-10-06 18:38:05.791966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5838ef1ecf1'
down_revision = 'db9bd888d36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('axial_order_known', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('axial_order_known')

    # ### end Alembic commands ###
