"""max in-copying angle of a tool, parting overshoot and groove dwell

Revision ID: d82ea01ebe01
Revises: 209c6b4145de
Create Date: 2026-10-09 18:40:11.695055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82ea01ebe01'
down_revision = '209c6b4145de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parting_overshoot_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('groove_dwell_s', sa.Float(), nullable=True))

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_ramp_angle', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('max_ramp_angle')

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('groove_dwell_s')
        batch_op.drop_column('parting_overshoot_mm')

    # ### end Alembic commands ###
