"""groove start diameter, insert width, operation depth

Revision ID: d9974d4be48c
Revises: 0a62a8b2ac24
Create Date: 2026-09-27 06:33:51.414551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9974d4be48c'
down_revision = '0a62a8b2ac24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_diameter', sa.Float(), nullable=True))

    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insert_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('depth', sa.Float(), nullable=True))

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insert_width', sa.Float(), nullable=True))

    # ### end Alembic commands ###

    # Seed grooving/parting tools stored the insert width in ap_min == ap_max; carry it over.
    op.execute(
        "UPDATE tool SET insert_width = ap_max "
        "WHERE type IN ('grooving', 'parting') AND insert_width IS NULL AND ap_min = ap_max"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('insert_width')

    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_column('depth')
        batch_op.drop_column('insert_width')

    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('start_diameter')

    # ### end Alembic commands ###
