"""dxf part and binding of drawing extractions

Revision ID: db9bd888d36a
Revises: 671327f4a6ea
Create Date: 2026-10-06 05:50:19.296202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9bd888d36a'
down_revision = '671327f4a6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dxf_part', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('binding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_extraction', schema=None) as batch_op:
        batch_op.drop_column('binding')
        batch_op.drop_column('dxf_part')

    # ### end Alembic commands ###
