"""where the cutting data of an operation come from

Revision ID: e304ff3c2963
Revises: 339c93bf0976
Create Date: 2026-10-09 05:28:34.854175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e304ff3c2963'
down_revision = '339c93bf0976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cutting_data_origin', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_column('cutting_data_origin')

    # ### end Alembic commands ###
